JUNKETEER_TWITTER_CONSUMER_KEY = "i6KISWAobHGDP045DPp9g"
JUNKETEER_TWITTER_CONSUMER_SECRET = "a3oBpKsAo3nVRFdxFW5YdtHybzj5sUXZHcRWtfqQU0"

Twitter.configure do |config|
  config.consumer_key = JUNKETEER_TWITTER_CONSUMER_KEY
  config.consumer_secret = JUNKETEER_TWITTER_CONSUMER_SECRET
end